-- This script was generated by a beta version of the ERD tool in pgAdmin 4.
-- Please log an issue at https://redmine.postgresql.org/projects/pgadmin4/issues/new if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.animal_dict
(
    animal_id integer NOT NULL DEFAULT nextval('animal_dict_animal_id_seq'::regclass),
    fk_animal_type integer NOT NULL,
    name character varying(100) COLLATE pg_catalog."default",
    fk_breed integer,
    fk_color1 integer,
    fk_color2 integer,
    date_of_bird timestamp with time zone,
    CONSTRAINT animal_dict_pkey PRIMARY KEY (animal_id)
);

CREATE TABLE IF NOT EXISTS public.animal_type
(
    id_type integer NOT NULL DEFAULT nextval('animal_type_id_type_seq'::regclass),
    animal_type character varying(50) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT animal_type_pkey PRIMARY KEY (id_type)
);

CREATE TABLE IF NOT EXISTS public.breed_dict
(
    id_breed integer NOT NULL DEFAULT nextval('breed_dict_id_breed_seq'::regclass),
    breed_type character varying(100) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT breed_dict_pkey PRIMARY KEY (id_breed)
);

CREATE TABLE IF NOT EXISTS public.colour_dict
(
    id_colour integer NOT NULL DEFAULT nextval('colour_dict_id_colour_seq'::regclass),
    name_colour character varying(100) COLLATE pg_catalog."default",
    CONSTRAINT colour_dict_pkey PRIMARY KEY (id_colour)
);

CREATE TABLE IF NOT EXISTS public.main_animals
(
    index integer,
    age_upon_outcome text COLLATE pg_catalog."default",
    animal_id text COLLATE pg_catalog."default",
    name text COLLATE pg_catalog."default",
    date_of_birth text COLLATE pg_catalog."default",
    outcome_month integer,
    outcome_year integer,
    id_breed integer,
    animal integer,
    id_colour integer,
    id_outcome_type integer,
    id_outcome_subtype integer
);

CREATE TABLE IF NOT EXISTS public.outcome_subtype
(
    id_outcome_subtype integer NOT NULL DEFAULT nextval('outcome_subtype_id_outcome_subtype_seq'::regclass),
    name_outcome_subtype character varying(100) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT outcome_subtype_pkey PRIMARY KEY (id_outcome_subtype)
);

CREATE TABLE IF NOT EXISTS public.outcome_type
(
    id_outcome_type integer NOT NULL DEFAULT nextval('outcome_type_id_outcome_type_seq'::regclass),
    name_outcome_type character varying(100) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT outcome_type_pkey PRIMARY KEY (id_outcome_type)
);

CREATE TABLE IF NOT EXISTS public.shelter_info
(
    id_shelter_info integer NOT NULL DEFAULT nextval('shelter_info_id_shelter_info_seq'::regclass),
    fk_animal_id integer NOT NULL,
    fk_id_outcome_subtype integer NOT NULL,
    outcome_month integer,
    outcome_year integer,
    fk_outcome_type integer,
    age_upon_outcome character varying(20) COLLATE pg_catalog."default",
    CONSTRAINT shelter_info_pkey PRIMARY KEY (id_shelter_info)
);

ALTER TABLE IF EXISTS public.animal_dict
    ADD CONSTRAINT animal_dict_fk_animal_type_fkey FOREIGN KEY (fk_animal_type)
    REFERENCES public.animal_type (id_type) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.animal_dict
    ADD CONSTRAINT animal_dict_fk_breed_fkey FOREIGN KEY (fk_breed)
    REFERENCES public.breed_dict (id_breed) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.animal_dict
    ADD CONSTRAINT animal_dict_fk_color1_fkey FOREIGN KEY (fk_color1)
    REFERENCES public.colour_dict (id_colour) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.animal_dict
    ADD CONSTRAINT animal_dict_fk_color2_fkey FOREIGN KEY (fk_color2)
    REFERENCES public.colour_dict (id_colour) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.shelter_info
    ADD CONSTRAINT shelter_info_fk_animal_id_fkey FOREIGN KEY (fk_animal_id)
    REFERENCES public.animal_dict (animal_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.shelter_info
    ADD CONSTRAINT shelter_info_fk_id_outcome_subtype_fkey FOREIGN KEY (fk_id_outcome_subtype)
    REFERENCES public.outcome_subtype (id_outcome_subtype) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.shelter_info
    ADD CONSTRAINT shelter_info_fk_outcome_type_fkey FOREIGN KEY (fk_outcome_type)
    REFERENCES public.outcome_type (id_outcome_type) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;

END;